# Media Migration Template with Perceptual Hashing
# Optimized for images and videos with duplicate detection

template_name: "Media Migration with Fingerprinting"
template_version: "1.0"
description: "Advanced media migration with perceptual hashing and duplicate detection"

# Path mappings
path_mappings:
  - source_path: "G:/n/gen7/manual_ingestion/civitai"
    destination_path: "G:/test_migration/civitai_test"
    preserve_structure: true
    create_directories: true

# File operation
operation: "copy"
conflict_resolution: "skip"

# Media file filtering
file_filter:
  include_patterns:
    # Images
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.bmp"
    - "*.tiff"
    - "*.tif"
    - "*.webp"
    - "*.heic"
    - "*.heif"
    - "*.raw"
    - "*.cr2"
    - "*.nef"
    - "*.dng"
    # Videos
    - "*.mp4"
    - "*.avi"
    - "*.mov"
    - "*.wmv"
    - "*.mkv"
    - "*.webm"
    - "*.flv"
    - "*.m4v"
    - "*.3gp"
    - "*.mpg"
    - "*.mpeg"
    # Other
    - "*.pdf"
    - "*.txt"
    - "*.json"
    - "*.xml"
  exclude_patterns:
    - "*.tmp"
    - "*.log"
    - "*.cache"
    - "Thumbs.db"
    - ".DS_Store"
    - "*.lnk"
    - "*.url"
    - "*.ini"
    - "desktop.ini"
  min_size: 1024  # 1KB minimum
  max_size: 2147483648  # 2GB maximum
  ignore_hidden: true
  ignore_system: true

# Full indexing with SHA256 hashing
indexing_mode: "full"
hash_algorithm: "sha256"
verify_integrity: true
index_output_path: "G:/test_migration/media_index.json"

# Performance settings optimized for media files
batch_size: 50      # Smaller batches for large media files
max_workers: 4      # Conservative for disk I/O
memory_limit: 4096  # 4GB for image processing

# Robust error handling
max_retries: 3
retry_delay: 2.0
continue_on_error: true

# Safety and validation
preserve_timestamps: true
preserve_permissions: true
dry_run: true  # Always start with dry run
validate_sources: true
validate_destinations: true

# Detailed logging for media processing
log_level: "INFO"
detailed_logging: true
progress_callback: true

# Media-specific custom parameters
custom_parameters:
  # Image fingerprinting settings
  enable_image_hashing: true
  image_hash_algorithm: "dhash"  # dhash, phash, ahash, whash
  image_hash_size: 8  # 8 = 64-bit, 16 = 256-bit
  image_similarity_threshold: 0.95
  
  # Video fingerprinting settings
  enable_video_hashing: true
  video_hash_algorithm: "videohash"
  video_similarity_threshold: 1.0  # Exact match for videos
  
  # Duplicate detection settings
  duplicate_detection_enabled: true
  hamming_distance_threshold: 2  # For image duplicates
  create_duplicate_report: true
  duplicate_report_path: "G:/test_migration/duplicate_report.json"
  
  # Processing options
  resize_large_images: false
  max_image_dimension: 4096
  skip_corrupted_files: true
  generate_thumbnails: false
  thumbnail_size: 256
  
  # Output options
  save_fingerprints: true
  fingerprint_output_path: "G:/test_migration/fingerprints.json"
  export_duplicate_list: true
  duplicate_list_path: "G:/test_migration/duplicates.txt"